# Generated by Django 6.0.1 on 2026-01-30 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleID', models.AutoField(primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=256)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Phone', models.CharField(max_length=20)),
                ('CreatedAt', models.DateTimeField(auto_now_add=True)),
                ('Role', models.ForeignKey(db_column='RoleID', default=1, on_delete=django.db.models.deletion.PROTECT, to='Account.role')),
            ],
        ),
    ]
