# Generated by Django 6.0.1 on 2026-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='Phone',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
