# Generated by Django 6.0.1 on 2026-01-31 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('AuthorID', models.AutoField(primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('GenreID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.AutoField(primary_key=True, serialize=False)),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('Title', models.CharField(max_length=255)),
                ('PublicationDate', models.DateField(blank=True, null=True)),
                ('CoverImageURL', models.URLField(blank=True, max_length=500, null=True)),
                ('Author', models.ForeignKey(db_column='AuthorID', on_delete=django.db.models.deletion.CASCADE, to='Books.author')),
                ('Genre', models.ForeignKey(db_column='GenreID', on_delete=django.db.models.deletion.PROTECT, to='Books.genre')),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('CopyID', models.AutoField(primary_key=True, serialize=False)),
                ('Status', models.CharField(default='Available', max_length=20)),
                ('Book', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('RentalID', models.AutoField(primary_key=True, serialize=False)),
                ('RentTime', models.DateTimeField(auto_now_add=True)),
                ('DueDate', models.DateTimeField()),
                ('Copy', models.ForeignKey(db_column='CopyID', on_delete=django.db.models.deletion.PROTECT, to='Books.bookcopy')),
                ('ProcessedByUser', models.ForeignKey(db_column='ProcessedByUserID', on_delete=django.db.models.deletion.PROTECT, related_name='processed_rentals', to='Account.account')),
                ('User', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, related_name='rentals', to='Account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('ReservationID', models.AutoField(primary_key=True, serialize=False)),
                ('ReservationTime', models.DateTimeField(auto_now_add=True)),
                ('ExpiryTime', models.DateTimeField()),
                ('Status', models.CharField(default='Active', max_length=20)),
                ('Book', models.ForeignKey(db_column='BookID', on_delete=django.db.models.deletion.CASCADE, to='Books.book')),
                ('User', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.CASCADE, to='Account.account')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('ReturnID', models.AutoField(primary_key=True, serialize=False)),
                ('ReturnTime', models.DateTimeField(auto_now_add=True)),
                ('ProcessedByUser', models.ForeignKey(db_column='ProcessedByUserID', on_delete=django.db.models.deletion.PROTECT, related_name='processed_returns', to='Account.account')),
                ('Rental', models.ForeignKey(db_column='RentalID', on_delete=django.db.models.deletion.CASCADE, to='Books.rental')),
            ],
        ),
    ]
