# Generated by Django 6.0.1 on 2026-02-01 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='Copy',
            field=models.ForeignKey(db_column='CopyID', on_delete=django.db.models.deletion.CASCADE, to='Books.bookcopy'),
        ),
    ]
